Repository woowa-techcamp-2020/market-12, pull requests merged in 2020-07, with the labels that each got.

#33 [수정] 회원가입 페이지 필수정보 입력칸 추가
  views/register.pug
Labels: FrontEnd

#34 회원가입 validation 함수 구현 및 input 필수항목에 required 추가
  public/javascripts/validations.js
  views/register.pug
Labels: FrontEnd

#35 회원가입 페이지 필수정보에 validation 적용 #32
  public/javascripts/register.js
  public/javascripts/validations.js
  views/register.pug
Labels: FrontEnd

#39 가입완료 페이지 작성
  lib/UserManager.js
  routes/index.js
  views/complete_register.pug
Labels: FrontEnd

#43 [수정] 백엔드 핸드폰 인증 api 추가
  routes/users.js
Labels: BackEnd

#45 [추가] 주소찾기 버튼 활성화 및 기능
  public/javascripts/register.js
  public/stylesheets/style.css
  views/register.pug
Labels: FrontEnd

#56 로고 만들고 페이지에 추가
  public/stylesheets/style.css
  views/complete_register.pug
  views/includes/logo.pug
  views/login.pug
  views/register.pug
Labels: FrontEnd

#62 [수정] 이메일 렌더링/validation 수정
  public/javascripts/register.js
  public/javascripts/validations.js
Labels: FrontEnd

#63 로그아웃 기능 추가
  routes/index.js
  views/index.pug
Labels: Api, BackEnd, FrontEnd

#64 [수정] 가입완료페이지 스타일 작업 #22
  public/stylesheets/style.css
  views/complete_register.pug
Labels: FrontEnd

#67 [추가] 아이디 체크 시 중복검사 #48
  public/javascripts/register.js
  public/javascripts/validations.js
  routes/users.js
Labels: Api, BackEnd, FrontEnd
